import { images } from "@/constants";

const dummyData = {
    categories: [
        { name: "Burgers", description: "Juicy grilled burgers" },
        { name: "Pizzas", description: "Oven-baked cheesy pizzas" },
        { name: "Burritos", description: "Rolled Mexican delights" },
        { name: "Sandwiches", description: "Stacked and stuffed sandwiches" },
        { name: "Wraps", description: "Rolled up wraps packed with flavor" },
        { name: "Bowls", description: "Balanced rice and protein bowls" },
    ],

    customizations: [
        // Toppings
        { $id: "custom-1", name: "Extra Cheese", price: 25, type: "topping", image:images.cheese },
        { $id: "custom-2", name: "Jalapeños", price: 20, type: "topping",image:images.cheese },
        { $id: "custom-3", name: "Onions", price: 10, type: "topping",image:images.onions },
        { $id: "custom-4", name: "Olives", price: 15, type: "topping",image:images.olives },
        { $id: "custom-5", name: "Mushrooms", price: 18, type: "topping",image:images.mushrooms },
        { $id: "custom-6", name: "Tomatoes", price: 10, type: "topping",image:images.tomatoes },
        { $id: "custom-7", name: "Bacon", price: 30, type: "topping",image:images.bacon },
        { $id: "custom-8", name: "Avocado", price: 35, type: "topping",image:images.avocado },

        // Sides
        { $id: "custom-9", name: "Coke", price: 30, type: "side", image:images.fries },
        { $id: "custom-10", name: "Fries", price: 35, type: "side", image:images.fries },
        { $id: "custom-11", name: "Garlic Bread", price: 40, type: "side", image:images.garlicBread },
        { $id: "custom-12", name: "Chicken Nuggets", price: 50, type: "side", image:images.chickenNuggets },
        { $id: "custom-13", name: "Iced Tea", price: 28, type: "side", image:images.icedTea },
        { $id: "custom-14", name: "Salad", price: 33, type: "side", image:images.salad },
        { $id: "custom-15", name: "Potato Wedges", price: 38, type: "side", image:images.potatoWedges },
        { $id: "custom-16", name: "Mozzarella Sticks", price: 45, type: "side", image:images.mozarellaSticks },
        { $id: "custom-17", name: "Sweet Corn", price: 25, type: "side", image:images.cheese },
        { $id: "custom-18", name: "Choco Lava Cake", price: 42, type: "side", image:images.chocoLavaCake },
    ],

    menu: [
        {
            $id: "item-0",
            name: "Classic Cheeseburger",
            description: "Beef patty, cheese, lettuce, tomato",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/044/844/600/large_2x/homemade-fresh-tasty-burger-with-meat-and-cheese-classic-cheese-burger-and-vegetable-ai-generated-free-png.png",
            price: 25.99,
            rating: 4.5,
            calories: 550,
            protein: 25,
            categories: "Burgers",
            menuCustomization: ["Extra Cheese", "Coke", "Fries", "Onions", "Bacon"],
            bunType: "Sesame Bun",
            deliveryFee: 3.99,
            preparingTime: 12,
        },
        {
            $id: "item-1",
            name: "Pepperoni Pizza",
            description: "Loaded with cheese and pepperoni slices",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/023/742/417/large_2x/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png",
            price: 30.99,
            rating: 4.7,
            calories: 700,
            protein: 30,
            categories: "Pizzas",
            menuCustomization: [
                "Extra Cheese",
                "Jalapeños",
                "Garlic Bread",
                "Coke",
                "Olives",
            ],
            bunType: "Thin Crust",
            deliveryFee: 4.99,
            preparingTime: 18,
        },
        {
            $id: "item-2",
            name: "Bean Burrito",
            description: "Stuffed with beans, rice, salsa",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/055/133/581/large_2x/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png",
            price: 20.99,
            rating: 4.2,
            calories: 480,
            protein: 18,
            categories: "Burritos",
            menuCustomization: ["Jalapeños", "Iced Tea", "Fries", "Salad"],
            bunType: "Flour Tortilla",
            deliveryFee: 3.99,
            preparingTime: 15,
        },
        {
            $id: "item-3",
            name: "BBQ Bacon Burger",
            description: "Smoky BBQ sauce, crispy bacon, cheddar",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/236/245/large_2x/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png",
            price: 27.5,
            rating: 4.8,
            calories: 650,
            protein: 29,
            categories: "Burgers",
            menuCustomization: ["Onions", "Fries", "Coke", "Bacon", "Avocado"],
            bunType: "Brioche Bun",
            deliveryFee: 4.99,
            preparingTime: 15,
        },
        {
            $id: "item-4",
            name: "Chicken Caesar Wrap",
            description: "Grilled chicken, lettuce, Caesar dressing",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/048/930/603/large_2x/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png",
            price: 21.5,
            rating: 4.4,
            calories: 490,
            protein: 28,
            categories: "Wraps",
            menuCustomization: ["Extra Cheese", "Coke", "Potato Wedges", "Tomatoes"],
            bunType: "Flour Tortilla",
            deliveryFee: 3.49,
            preparingTime: 12,
        },
        {
            $id: "item-5",
            name: "Grilled Veggie Sandwich",
            description: "Roasted veggies, pesto, cheese",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/047/832/012/large_2x/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png",
            price: 19.99,
            rating: 4.1,
            calories: 420,
            protein: 19,
            categories: "Sandwiches",
            menuCustomization: ["Mushrooms", "Olives", "Mozzarella Sticks", "Iced Tea"],
            bunType: "Artisan Bread",
            deliveryFee: 3.49,
            preparingTime: 10,
        },
        {
            $id: "item-6",
            name: "Double Patty Burger",
            description: "Two juicy beef patties and cheese",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/359/627/large_2x/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png",
            price: 32.99,
            rating: 4.9,
            calories: 720,
            protein: 35,
            categories: "Burgers",
            menuCustomization: [
                "Extra Cheese",
                "Onions",
                "Fries",
                "Coke",
                "Chicken Nuggets",
            ],
            bunType: "Sesame Bun",
            deliveryFee: 4.99,
            preparingTime: 15,
        },
        {
            $id: "item-7",
            name: "Paneer Tikka Wrap",
            description: "Spicy paneer, mint chutney, veggies",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/057/913/530/large_2x/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png",
            price: 23.99,
            rating: 4.6,
            calories: 470,
            protein: 20,
            categories: "Wraps",
            menuCustomization: ["Jalapeños", "Tomatoes", "Salad", "Fries", "Iced Tea"],
            bunType: "Spinach Tortilla",
            deliveryFee: 3.49,
            preparingTime: 15,
        },
        {
            $id: "item-8",
            name: "Mexican Burrito Bowl",
            description: "Rice, beans, corn, guac, salsa",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/057/466/374/large_2x/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png",
            price: 26.49,
            rating: 4.7,
            calories: 610,
            protein: 24,
            categories: "Bowls",
            menuCustomization: ["Avocado", "Sweet Corn", "Salad", "Iced Tea"],
            bunType: "Rice Base",
            deliveryFee: 4.49,
            preparingTime: 18,
        },
        {
            $id: "item-9",
            name: "Spicy Chicken Sandwich",
            description: "Crispy chicken, spicy sauce, pickles",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/051/814/008/large_2x/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png",
            price: 24.99,
            rating: 4.3,
            calories: 540,
            protein: 26,
            categories: "Sandwiches",
            menuCustomization: [
                "Jalapeños",
                "Onions",
                "Fries",
                "Coke",
                "Choco Lava Cake",
            ],
            bunType: "Whole Wheat Bread",
            deliveryFee: 3.99,
            preparingTime: 12,
        },
        {
            $id: "item-10",
            name: "Classic Margherita Pizza",
            description: "Tomato, mozzarella, fresh basil",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/058/700/845/large_2x/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png",
            price: 26.99,
            rating: 4.1,
            calories: 590,
            protein: 21,
            categories: "Pizzas",
            menuCustomization: ["Extra Cheese", "Olives", "Coke", "Garlic Bread"],
            bunType: "Thick Crust",
            deliveryFee: 4.99,
            preparingTime: 20,
        },
        {
            $id: "item-11",
            name: "Protein Power Bowl",
            description: "Grilled chicken, quinoa, veggies",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/056/106/379/large_2x/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png",
            price: 29.99,
            rating: 4.8,
            calories: 580,
            protein: 38,
            categories: "Bowls",
            menuCustomization: ["Avocado", "Salad", "Sweet Corn", "Iced Tea"],
            bunType: "Quinoa Base",
            deliveryFee: 4.49,
            preparingTime: 20,
        },
        {
            $id: "item-12",
            name: "Paneer Burrito",
            description: "Paneer cubes, spicy masala, rice, beans",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/056/565/254/large_2x/burrito-with-cauliflower-and-vegetables-free-png.png",
            price: 24.99,
            rating: 4.2,
            calories: 510,
            protein: 22,
            categories: "Burritos",
            menuCustomization: ["Jalapeños", "Fries", "Garlic Bread", "Coke"],
            bunType: "Flour Tortilla",
            deliveryFee: 3.99,
            preparingTime: 18,
        },
        {
            $id: "item-13",
            name: "Chicken Club Sandwich",
            description: "Grilled chicken, lettuce, cheese, tomato",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/364/135/large_2x/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png",
            price: 27.49,
            rating: 4.5,
            calories: 610,
            protein: 31,
            categories: "Sandwiches",
            menuCustomization: ["Bacon", "Tomatoes", "Mozzarella Sticks", "Iced Tea"],
            bunType: "Artisan Bread",
            deliveryFee: 3.99,
            preparingTime: 12,
        },
    ],
};

export default dummyData;